### ISSUE TITLE
Nothing in master?

### ISSUE THREAD

**Issue by reppolice** [ArthurGareginyan/mycyberuniverse#1]
Almost embarrassed to ask because the answer may be basic for web pros, but why is development taking place in the other branch? Thanks!

**Comment by ArthurGareginyan** [comment]
This website placed in the "gh-pages" branch because it is created as a project page instead of user/organization page.

GitHub allows us to create a web pages in any of our repository by placing it in the "gh-pages" branch, it is called "project page". See the following page: [https://help.github.com/articles/user-organization-and-project-pages/](https://help.github.com/articles/user-organization-and-project-pages/)
